Algoritmo "verificar numero do intervalo de 200"
// Turma: 1ºC
// Descrição   : Verificar numero
// Autor(a)    : Evellyn de S. Feliciano
// Data atual  : 25/05/2023
Var
numero: real

Inicio
escreval("Digite seu numero")
leia(numero)

se(numero>=100)entao
     se(numero<=200)entao
          escreval("seu numero esta no intervalo")
     senao
          escreval("seu numero está fora do intervalo")
     fimse
fimse

Fimalgoritmo
